name: weatherApp_rffrench
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_dotenv: ^2.1.0 # .env variables to hide API Key
  loading_indicator: ^1.1.0 # Loading icon
  geolocator: ^5.3.2+2 # Location of the device

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env

  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-Bold.ttf
          weight: 700
        - asset: fonts/Dosis-Medium.ttf
          weight: 500
        - asset: fonts/Dosis-Light.ttf
          weight: 300
        - asset: fonts/Dosis-ExtraLight.ttf
          weight: 200
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        
  
